# https://github.com/marketplace/actions/md2zhihu
# https://github.com/drmingdrmer/md2zhihu

name: md2zhihu
on:
  push:
    branches: [ main, master ]
    paths:
      - '_posts/**'
      - '_includes/**'
jobs:
  md2zhihu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: drmingdrmer/md2zhihu@main
      env:
        GITHUB_USERNAME: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        pattern: >
            _posts/*.markdown